language: php
php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly
  - nightly
matrix:
  allow_failures:
    - php: 5.2
    - php: 5.3
    - php: 7.0
    - php: hhvm
    - php: hhvm-nightly
    - php: nightly
before_install:
  - composer self-update
install:
  - travis_retry composer install --no-interaction